# Render.com Deployment Configuration
# MW Design Studio - Client Intake System v2.0

version: 1

services:
  # Main FastAPI Application
  - type: web
    name: mw-design-client-intake-v2
    env: python
    plan: starter  # Free tier to start
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    
    # Environment Variables
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mw-design-postgres-v2
          property: connectionString
    
    # Health Check
    healthCheckPath: /health
    
    # Auto-deploy from GitHub
    autoDeploy: true

# Database Configuration
databases:
  - name: mw-design-postgres-v2
    databaseName: mw_design_intake_v2
    user: mw_admin
    plan: starter  # Free PostgreSQL instance